# Generated by Django 2.1.5 on 2019-02-02 08:41

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('year', models.CharField(max_length=100)),
                ('track_count', models.IntegerField(verbose_name=11)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(verbose_name=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'music_playlists',
            },
        ),
        migrations.CreateModel(
            name='PlayListDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.PlayList')),
            ],
            options={
                'db_table': 'music_playlists_details',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('label_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=dashboard.models.upload_cover_image)),
                ('song', models.FileField(blank=True, null=True, upload_to=dashboard.models.upload_song)),
                ('duration', models.CharField(max_length=10)),
                ('stream', models.IntegerField(verbose_name=11)),
                ('streamed', models.IntegerField(verbose_name=11)),
                ('amount', models.IntegerField(verbose_name=11)),
                ('featured_artist', models.CharField(max_length=100)),
                ('contributors', models.CharField(max_length=100)),
                ('recording_year', models.CharField(max_length=100)),
                ('status', models.BooleanField(verbose_name=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Album')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.Country')),
                ('push_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.LocalArea')),
                ('push_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='UserEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_currency', models.CharField(max_length=50)),
                ('earned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Track')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_earning',
            },
        ),
        migrations.AddField(
            model_name='playlistdetail',
            name='track_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Track'),
        ),
        migrations.AddField(
            model_name='playlistdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
