# Generated by Django 2.1.5 on 2019-02-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190226_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songlist',
            name='country',
        ),
    ]
