# Generated by Django 2.1.5 on 2019-02-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_songlist_country'),
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
